FESTIVALS = {
    'electric-forest-2026': {
        'name': 'Electric Forest 2026',
        'dates': 'June 25–28, 2026',
        'location': 'Rothbury, MI',
        'artists': [
            'all:Lo Collective', 'Alleycvt', 'Andy C', 'Avello', 'Bardo',
            'Bipolar Sunshine', 'Bob Moses', 'Bombargo', 'Bricknasty', 'Brunello',
            'Cain Culto', 'Capochino', 'Casey Club', 'Channel Tres', 'Chmura',
            'Chris Lake', 'Chris Luno', 'Close Friends Only', 'Costa', 'Couch',
            'Creg', 'D.O.D', 'Daily Bread', 'Daniel Allan', 'Daniel Donatos Cosmic Country',
            'Deadtronica', 'Devault', 'Disco Lines', 'Dixons Violin', 'DJ Diesel',
            'Dogs In A Pile', 'Effin', 'Eggy', 'Eli Brown', 'EOTO', 'Excision',
            'Frost Children', 'Galantis', 'Ganja White Night', 'GRiZ', 'Hershe',
            'Heyz', 'ILLENIUM', 'Iniko', 'Inji', 'ISOxo', 'Ivy Lab',
            'Jackie Hollander', 'Jean Dawson', 'Jigitz', 'Jkyl & Hyde', 'Kai Wachi',
            'Kaleena Zanders', 'Kaskade', 'Lane 8', 'Laszewo', 'Levity',
            'LSD Clownsystem', 'LSDream', 'Lyrah', 'Madeon', 'Magoo',
            'Mary Droppinz', 'MCR-T', 'Midnight Generation', 'Mild Minds', 'Motifv',
            'MPH', 'Muzz', 'Night Tapes', 'Nikita the Wicked', 'Nitepunk',
            'Odd Mob', 'Omnom', 'Oppidan', 'Passion Pit', 'Probcause',
            'Purple Disco Machine', 'Qrion', 'Ranger Trucco', 'RAVENSCOON',
            'Richard Finger', 'Rio Kosta', 'Riot', 'River Tiber', 'Rochelle Jordan',
            'Saint Ludo', 'Sam Gellaitry', 'Sammy Virji', 'SBTRKT', 'Shima',
            'Ship Wrek', 'Shpongle', 'Sidepiece', 'Sippy', 'Snow Wife',
            'Starjunk 95', 'Steller', 'Stolen Gin', 'Sullivan King', 'Supertaste',
            'Swimming Paul', 'The Flints', 'The Sponges', 'The String Cheese Incident',
            'Tiffany Day', 'Tourist', 'Underscores', 'Vandelux', 'Vincent Antone',
            'Wax Monkey', 'Wes Mills', 'Westend', 'Whethan', 'Wilkinson',
            'Wooli', 'Yaeji', 'T-Pain',
        ],
    },
}
